### ISSUE TITLE
mac folder fail

### ISSUE THREAD

**Issue by 3pointedit** [gregzaal/filmic-blender-add-on#1]
Addon runs in B2.78 2016-10-13 Hash:87a7149 on MacBook Pro OSx 10.11.6

Addon fails after download as it stores colormanagement filter in the wrong folder
The addon created a 2.78 folder and datafiles folder inside the MacOS folder instead of finding the original folders. It also did not rename the original folder (because it couldn't find it I guess). 

I also could not know that the download was completed unless I exposed the Info bar at the top of blender. To fix it I just renamed the old CM folder and moved the new one into the correct folder.

**Comment by gregzaal** [comment]
Interesting. I don't have a Mac to test this, so I'll need some help finding the right path...

Where is the colormanagement folder on mac? On windows it's just in the Blender folder (`bpy.app.binary_path + 2.78/datafiles/colormanagement`).

**Comment by gregzaal** [comment]
Ok maybe fixed in a78c772a, can you [download again](https://raw.githubusercontent.com/gregzaal/filmic-blender-add-on/master/filmic_blender.py) and see if it works?

**Comment by gregzaal** [comment]
I think this is working, let me know if it's not.

**Comment by 3pointedit** [comment]
Working now. Thanks Greg. I never noticed the little alert up the top, probably because it did not complete the task correctly. I wonder if you should print a fail if it cannot find the correct path?

**Comment by gregzaal** [comment]
Yeah, some nicer error handling is needed. atm if there's no internet, the folder has the wrong permissions or a bunch of other possible things, it'll just say "Check your internet" :P
