### ISSUE TITLE
Filmic and those Film Filters we love

### ISSUE THREAD

**Issue by enzyme69** [gregzaal/filmic-blender-add-on#3]
Hi Greg, the Filmic Button to quickly update and install is cool. Just wondering though, is there anyway we can somewhat quickly switch back to original default FILM FILTER like Agfa, Fuji, etc. I wanted to use both Filmic and the Film Filter.

If I remove the Filmic, will it revert back to the original with film? If yes, maybe I can do that every time... a bit of hassle though still.

**Comment by gregzaal** [comment]
No idea, ask on the original [filmic github repo](https://github.com/sobotka/filmic-blender).
