### ISSUE TITLE
Failed to download Filmic Blender, maybe check your internet connection?

### ISSUE THREAD

**Issue by peterrobie** [gregzaal/filmic-blender-add-on#4]
On line 45 blender tries to get the file and returns a generic error on line 48. Obviously no issues getting on the internet.

I'm running MacOS and get the following output in the terminal.
```
sudo blender-2.78.04/blender.app/Contents/MacOS/blender 
Password:
found bundled python: blender-2.78.04/blender.app/Contents/MacOS/../Resources/2.78/python
URL: https://github.com/sobotka/filmic-blender/archive/master.zip 
Download Path: /tmp/blender_OerahY/filmic_blender.zip
```

After doing some more research it came up with an error on the SSL Certificate.

I'm going through and manually installing Filmic, but I'll look into this more later on.

**Comment by gregzaal** [comment]
Maybe a temporary server glitch with github, nothing we can do about that.

There is another permissions issue on OSX (#2) but that's more to do with where blender is installed, so probably not related.

**Comment by naseemshanbour** [comment]
its a network security issue,i found a way around this i just copied the new installed color management folder from an off grid computer  and replaced the old one at my workstation, it worked :yum:
